In [12]:
import pandas as pd
import numpy as np

In [2]:
!conda install pandas -y

Solving environment: done

## Package Plan ##

  environment location: /Users/brian/anaconda/envs/advanced_python

  added / updated specs: 
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-0.23.1              |   py36h1702cab_0        11.0 MB

The following NEW packages will be INSTALLED:

    pandas: 0.23.1-py36h1702cab_0


pandas-0.23.1        | 11.0 MB | ####################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


In [ ]:
def read_data(fname, header=True):

In [3]:
import csv

In [9]:
def str2float(txt):
    try:
        return float(txt)
    except:
        return np.nan

In [23]:
def read_data(fname, header=True):
    data = []
    with open(fname) as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|')
        if header:
            h = next(reader)
        else:
            h = []
        for row in reader:
            data.append(list(map(str2float,row)))
    return np.array(data), h
read_data('Class_Ozone_Data.csv')

(array([[4.90351001e+11, 4.36460000e+04, 1.30768701e+03, 2.75572879e+01,
         5.25443555e+01],
        [4.90351003e+11, 3.57750000e+04, 1.29685205e+03, 2.62843088e+01,
         5.47278560e+01],
        [4.90351003e+11, 3.82810000e+04, 1.28972046e+03, 2.76850720e+01,
         5.27117697e+01],
        [4.90351006e+11, 6.40910000e+04, 1.30192676e+03, 2.75997767e+01,
         5.30708101e+01],
        [4.90351006e+11, 3.70830000e+04, 1.29685205e+03, 2.88026529e+01,
         5.50963624e+01],
        [4.90351006e+11, 2.15000000e+04, 1.30186096e+03, 2.67737465e+01,
         5.52121783e+01],
        [4.90351008e+11, 4.11540000e+04, 1.32106982e+03, 2.70460296e+01,
         5.21052474e+01],
        [4.90351008e+11, 3.37720000e+04, 1.32106982e+03, 2.57124834e+01,
         5.22588764e+01],
        [4.90351008e+11, 3.75660000e+04, 1.32106982e+03, 2.68710378e+01,
         4.89813398e+01],
        [4.90351014e+11, 3.34380000e+04, 1.41046228e+03, 2.66166667e+01,
         5.33750000e+01],
        [4

In [24]:
data, h = np.array(read_data('Class_Ozone_Data.csv'))

In [29]:
data[:10,(1,3)]

array([[4.36460000e+04, 2.75572879e+01],
       [3.57750000e+04, 2.62843088e+01],
       [3.82810000e+04, 2.76850720e+01],
       [6.40910000e+04, 2.75997767e+01],
       [3.70830000e+04, 2.88026529e+01],
       [2.15000000e+04, 2.67737465e+01],
       [4.11540000e+04, 2.70460296e+01],
       [3.37720000e+04, 2.57124834e+01],
       [3.75660000e+04, 2.68710378e+01],
       [3.34380000e+04, 2.66166667e+01]])

In [30]:
data[:10,(0,3)]

array([[4.90351001e+11, 2.75572879e+01],
       [4.90351003e+11, 2.62843088e+01],
       [4.90351003e+11, 2.76850720e+01],
       [4.90351006e+11, 2.75997767e+01],
       [4.90351006e+11, 2.88026529e+01],
       [4.90351006e+11, 2.67737465e+01],
       [4.90351008e+11, 2.70460296e+01],
       [4.90351008e+11, 2.57124834e+01],
       [4.90351008e+11, 2.68710378e+01],
       [4.90351014e+11, 2.66166667e+01]])