In [94]:
import numpy as np
import numpy.linalg as la

## Key debugging points

* How is the arthimetic for these arrays being computed?
    * Array casting
    * dtype, astype
* Copying values/reference

In [38]:
def find_pivot(c):
    print(c.shape)
    m = c.shape[0]
    maxv = c[0]
    argmax = 0
    for i in range(1,m):
        print(c[i])
        if c[i] > maxv:
            maxv = c[i]
            argmax = i
        print("i=%d"%i)
        print("argmax=%f"%argmax)
    return argmax

In [39]:
def find_pivot2(c):
    return np.argmax(c[])

In [40]:
find_pivot(A)

(3, 3)
[[3 8 1]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
%debug

> <ipython-input-38-54a136c2f8cc>(8)find_pivot()
      6     for i in range(1,m):
      7         print(c[i])
----> 8         if c[i] > maxv:
      9             maxv = c[i]
     10             argmax = i

ipdb> p c[i]
matrix([[3, 8, 1]])
ipdb> q


In [96]:
A = np.matrix([[1,2,1],[3,8,1],[0,4,1]])
A

matrix([[1, 2, 1],
        [3, 8, 1],
        [0, 4, 1]])

In [97]:
b = np.matrix([2,12,2]).transpose()
b

matrix([[ 2],
        [12],
        [ 2]])

In [98]:
def swap_rows(a,i,j):
    A = np.matrix.copy(a)
    tmp = A[i,:].copy()
    A[i,:] = A[j,:].copy()
    A[j,:] = tmp
    return A

In [99]:
def pivot_rows(a,b,k):
    # find pivot
    print("pivot_rows")
    pivot_row = find_pivot(a[k:,k]) + k
    print("exchange %d with %d"%(k,pivot_row))
    print(a)
    A = swap_rows(a,k,pivot_row)
    b = swap_rows(b,k,pivot_row)
    print(A)
    return A,b

In [100]:
x = np.matrix([[1],[3],[7],[2],[-1]])

In [101]:
x.shape

(5, 1)

In [128]:
def gaussian_elimination2(a,_b):
    A = np.matrix.copy(a).astype(np.float64)
    b = np.matrix.copy(_b).astype(np.float64)
    print("dtype of A",A.dtype)
    m = A.shape[0]
    for k in range(0,m-1):
        print("processing row k=%d"%k)
        A,b = pivot_rows(A,b,k)
        
        print("pivoted A")
        print(A)
        for i in range(k+1,m):
            print("Pivot",A[k,k])
            
            f = A[i,k]/A[k,k]
            #print(1/0)
            print("Factor",f)
            A[i,:] = A[i,:]-f*A[k,:]
            print("modifing row %d"%i)
            print(A)
            print(A.dtype)
            b[i] = b[i] -f*b[k]
        print("Modified A")
        print(A)
        print("*"*42)
    return A,b

In [130]:
U, b_ = gaussian_elimination2(A,b)

dtype of A float64
processing row k=0
pivot_rows
(3, 1)
[[3.]]
i=1
argmax=1.000000
[[0.]]
i=2
argmax=1.000000
exchange 0 with 1
[[1. 2. 1.]
 [3. 8. 1.]
 [0. 4. 1.]]
[[3. 8. 1.]
 [1. 2. 1.]
 [0. 4. 1.]]
pivoted A
[[3. 8. 1.]
 [1. 2. 1.]
 [0. 4. 1.]]
Pivot 3.0
Factor 0.3333333333333333
modifing row 1
[[ 3.          8.          1.        ]
 [ 0.         -0.66666667  0.66666667]
 [ 0.          4.          1.        ]]
float64
Pivot 3.0
Factor 0.0
modifing row 2
[[ 3.          8.          1.        ]
 [ 0.         -0.66666667  0.66666667]
 [ 0.          4.          1.        ]]
float64
Modified A
[[ 3.          8.          1.        ]
 [ 0.         -0.66666667  0.66666667]
 [ 0.          4.          1.        ]]
******************************************
processing row k=1
pivot_rows
(2, 1)
[[4.]]
i=1
argmax=1.000000
exchange 1 with 2
[[ 3.          8.          1.        ]
 [ 0.         -0.66666667  0.66666667]
 [ 0.          4.          1.        ]]
[[ 3.          8.          1.        ]
 

In [131]:
def backward_solve(U, b):
    x = np.zeros(b.shape)
    m = U.shape[0]
    for i in range(m-1,-1,-1):
        s = b[i]
        print("row %d"%i)
        print(s)
        for j in range(i+1,m):
            s = s-U[i,j]*x[j]
            print(s)
        x[i] = s/U[i,i]
        print("x[i]=%f"%x[i])
    return x

In [132]:
backward_solve(U,b_)

row 2
[[-1.66666667]]
x[i]=-2.000000
row 1
[[2.]]
[[4.]]
x[i]=1.000000
row 0
[[12.]]
[[4.]]
[[6.]]
x[i]=2.000000


array([[ 2.],
       [ 1.],
       [-2.]])

In [ ]:
A.astype(np.int64)