# Gaussian Elimination

\begin{eqnarray}
\begin{array}{rcrcrc@{\qquad}l}
x & + & 2y & + & z = & 2 & (a)\\
3x & + & 8y & + & z = & 12 & (b) \\
   & & 4y & + & z = & 2 & (c)
\end{array}
\end{eqnarray}

\begin{equation}
\begin{bmatrix}
\begin{array}{rrr{\qquad}1}
1 & 2 & 1\\
3 & 8 & 1\\
0 & 4 & 1
\end{array}
\end{bmatrix}
\end{equation}

## Algorithm (from http://www.math-cs.gordon.edu/courses/ma342/handouts/gauss.pdf)

Following the pseudocode available at the above link, we are going to break our algorithm into three parts:

1. Gaussian Elimination
2. Forward Elimination
3. Backward Solve

### Gaussian Elimination

The gist of this step is to transform our matrix to an upper triangular matrix by finding **pivots**, using the pivots to determine multiplicative factors

![Gaussian Elimination Pseudocode](./gaussian_elimination.jpg)

**Note:** this pseudocode assumes indexing starts at one. We will need to modify this for Python which starts at zero.

For the $k^{th}$ row we identify the $k^{th}$ column; this is the **pivot**. For each row $i; i > k$, we find the multiplier ($f_{ki}$) such that when we multiply row $k$ by

In [42]:
import numpy as np

def gaussian_elimination1(a):
    A = np.matrix.copy(a)
    m = A.shape[0]
    for k in range(0,m):
        for i in range(k+1,m):
            f = A[i,k]/A[k,k]
            A[i,:] = A[i,:]-m*A[k,:]
    return A
    

In [85]:
A = np.matrix([[1,2,1],[3,8,1],[0,4,1]])
A

matrix([[1, 2, 1],
        [3, 8, 1],
        [0, 4, 1]])

In [20]:
U = gaussian_elimination1(A)

In [21]:
type(U)

numpy.matrixlib.defmatrix.matrix

In [22]:
U

matrix([[ 1,  2,  1],
        [ 0,  2, -2],
        [-3, -8,  4]])

![forward_elimination](./forward_elimination.png)

In [45]:
def gaussian_elimination2(a,_b):
    A = np.matrix.copy(a)
    b = np.matrix.copy(_b)
    m = A.shape[0]
    for k in range(0,m-1):
        for i in range(k+1,m):
            f = A[i,k]/A[k,k]
            A[i,:] = A[i,:]-f*A[k,:]
            b[i] = b[i] -f*b[k]
    return A,b

In [46]:
b = np.matrix([2,12,2]).transpose()

In [47]:
b

matrix([[ 2],
        [12],
        [ 2]])

In [54]:
U,b_

(matrix([[ 1,  2,  1],
         [ 0,  2, -2],
         [ 0,  0,  5]]), matrix([[  2],
         [  6],
         [-10]]))

In [48]:
U, b_ = gaussian_elimination2(A,b)

In [55]:
b_

matrix([[  2],
        [  6],
        [-10]])

## Backward Substitution
![backward substitution](./backward_solve.png)

### Hints

1. Think about the limits of the `range` function in Python

In [81]:
def backward_solve(U, b):
    x = np.zeros(b.shape)
    m = U.shape[0]
    for i in range(m-1,-1,-1):
        s = b[i]
        print("row %d"%i)
        print(s)
        for j in range(i+1,m):
            s = s-U[i,j]*x[j]
            print(s)
        x[i] = s/U[i,i]
        print("x[i]=%f"%x[i])
    return x

In [82]:
b_

matrix([[  2],
        [  6],
        [-10]])

In [83]:
backward_solve(U,b_)

row 2
[[-10]]
x[i]=-2.000000
row 1
[[6]]
[[2.]]
x[i]=1.000000
row 0
[[2]]
[[0.]]
[[2.]]
x[i]=2.000000


array([[ 2.],
       [ 1.],
       [-2.]])

## How can we check our solution?

In [39]:
import numpy.linalg as la

In [40]:
la.solve(A,b)

matrix([[ 2.],
        [ 1.],
        [-2.]])

## Are there any assumptions we made in our solution?