In [3]:
import numpy as np
import numpy.linalg as la

## Key debugging points

* How is the arthimetic for these arrays being computed?
    * Array casting
    * dtype, astype
* Copying values/reference

In [4]:
def find_pivot(c):
    print(c.shape)
    m = c.shape[0]
    maxv = c[0]
    argmax = 0
    for i in range(1,m):
        print(c[i])
        if c[i] > maxv:
            maxv = c[i]
            argmax = i
        print("i=%d"%i)
        print("argmax=%f"%argmax)
    return argmax

In [5]:
def find_pivot2(c):
    return np.argmax(c)

In [7]:
A = np.matrix([[1,2,1],[3,8,1],[0,4,1]])
A

matrix([[1, 2, 1],
        [3, 8, 1],
        [0, 4, 1]])

In [8]:
b = np.matrix([2,12,2]).transpose()
b

matrix([[ 2],
        [12],
        [ 2]])

In [9]:
def pivot_rows(a,b,k):
    # find pivot
    pr = find_pivot2(a[k:,k]) + k
    p = np.matrix(np.identity(a.shape[0], dtype=np.float64))
    p[pr,pr] = 0.0
    p[k,k] = 0.0
    p[k,pr] = 1
    p[pr,k] = 1
    A = p*a
    b = p*b
    print(A)
    return A,b

In [10]:
x = np.matrix([[1],[3],[7],[2],[-1]])

In [11]:
x.shape

(5, 1)

In [12]:
def gaussian_elimination3(a,_b):
    A = np.matrix.copy(a).astype(np.float64)
    b = np.matrix.copy(_b).astype(np.float64)
    m = A.shape[0]
    for k in range(0,m-1):
        A,b = pivot_rows(A,b,k)
        

        for i in range(k+1,m):
            
            f = A[i,k]/A[k,k]
            A[i,:] = A[i,:]-f*A[k,:]
            b[i] = b[i] -f*b[k]
    return A,b

In [13]:
U, b_ = gaussian_elimination3(A,b)

[[3. 8. 1.]
 [1. 2. 1.]
 [0. 4. 1.]]
[[ 3.          8.          1.        ]
 [ 0.          4.          1.        ]
 [ 0.         -0.66666667  0.66666667]]


In [14]:
U

matrix([[3.        , 8.        , 1.        ],
        [0.        , 4.        , 1.        ],
        [0.        , 0.        , 0.83333333]])

In [15]:
def backward_solve(U, b):
    x = np.zeros(b.shape)
    m = U.shape[0]
    for i in range(m-1,-1,-1):
        s = b[i]
        print("row %d"%i)
        print(s)
        for j in range(i+1,m):
            s = s-U[i,j]*x[j]
            print(s)
        x[i] = s/U[i,i]
        print("x[i]=%f"%x[i])
    return x

In [16]:
backward_solve(U,b_)

row 2
[[-1.66666667]]
x[i]=-2.000000
row 1
[[2.]]
[[4.]]
x[i]=1.000000
row 0
[[12.]]
[[4.]]
[[6.]]
x[i]=2.000000


array([[ 2.],
       [ 1.],
       [-2.]])

In [ ]:
p = np.matrix([[0,1,0],[1,0,0],[0,0,1]])

In [ ]:
p*A

In [ ]:
np.matrix(np.identity(3))

In [ ]:
help(np.identity)