# Numpy 실습 NOTE 
- python numpy 강좌(TeamLab in Youtube)
- made by MinDong Sung M.D.

In [4]:
import numpy as np

## Creation_1

### Array Creation

In [5]:
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [6]:
type(test_array)

numpy.ndarray

In [7]:
type(test_array[3])

numpy.float64

In [8]:
# data type
test_array.dtype

dtype('float64')

In [9]:
# data shape
test_array.shape

(4,)

### Matrix Creation

In [10]:
matrix = [[1,2,3,4],[1,2,5,8],[2,4,5,3]]
np.array(matrix, int).shape

(3, 4)

### Tensor Creation(3rd order tensor)

In [11]:
tensor = [[[1,2,3,4],[1,2,5,8],[2,4,5,3]],
    [[1,2,3,4],[1,2,5,8],[2,4,5,3]],
    [[1,2,3,4],[1,2,5,8],[2,4,5,3]],
    [[1,2,3,4],[1,2,5,8],[2,4,5,3]]]

np.array(tensor, int).shape

(4, 3, 4)

## Handling shape 

### RESHAPE

In [12]:
test_matrix = [[1,2,3,4],[2,3,4,5]]
np.array(test_matrix).shape

(2, 4)

In [13]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 2, 3, 4, 5])

In [14]:
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5]])

In [15]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[2, 3],
        [4, 5]]])

### FLATTEN

In [16]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 2, 3, 4, 5])

## Indexing

In [17]:
test_example = np.array([[1,2,3],[4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
test_example[0,0]

1

In [19]:
test_example[0][0]

1

In [20]:
test_example[0][1] = 10
test_example

array([[ 1, 10,  3],
       [ 4,  5,  6]])

## Slicing

In [21]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)

In [22]:
a[:,1:3]

array([[2, 3],
       [7, 8]])

In [23]:
a[1,2:]

array([ 8,  9, 10])

In [24]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [25]:
a[:,0:4:2] ## step도 가능하다

array([[1, 3],
       [6, 8]])

## Creation_2

### ARANGE

In [26]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
np.arange(0,5,0.5).reshape(2,-1)

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

In [28]:
np.arange(0,5,0.5).tolist() 

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

range는 floating type이 지원되지 않으나 
np.arange는 floting type도 지원되어 
list를 얻을 때는 .tolist()라는 명령어를 이용한다. 

### ZEROS

In [29]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [30]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ONES

In [31]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### EMPTY

memory를 초기화시켜주지 않음.

In [32]:
np.empty((2,4))

array([[4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323]])

### SOMETHING_LIKE(ZEORS, ONES, EMPTY)

In [33]:
test_matrix = np.arange(30).reshape(5,6)
test_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [35]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Linear Algebra

### IDENTITY

In [36]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

### EYE

In [37]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [38]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3,5,k=2) ## k는 starting point

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### DIAG

In [40]:
matrix=np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

### RANDOM.UNIFORM / RANDOM.NORMAL

In [41]:
np.random.uniform(0,1,10).reshape(2,5) ## 균등분포(처음과 끝)

array([[0.8441473 , 0.23957579, 0.50546281, 0.19344361, 0.47835295],
       [0.85505907, 0.3814583 , 0.79075858, 0.33937659, 0.80603281]])

In [42]:
np.random.normal(0,1,10).reshape(2,5) ## Normal 분포(mean, sd)

array([[ 0.7640967 , -0.31498324, -1.22271313, -0.65779633,  0.16658276],
       [-1.25309958, -1.14570517,  0.03038092,  0.64166419, -0.37900106]])

## Operation functions

### SUM

In [43]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
test_array.sum(dtype = np.float)

55.0

In [45]:
test_array = np.arange(1,13).reshape(3,4)

In [47]:
test_array.sum(axis = 1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [52]:
test_tensor = np.arange(60).reshape(3,4,5)

In [53]:
test_tensor

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [54]:
test_tensor.sum(axis =0), test_tensor.sum(axis =1), test_tensor.sum(axis =2) 

(array([[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]]), array([[ 30,  34,  38,  42,  46],
        [110, 114, 118, 122, 126],
        [190, 194, 198, 202, 206]]), array([[ 10,  35,  60,  85],
        [110, 135, 160, 185],
        [210, 235, 260, 285]]))

### MEAN / STD

In [55]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
test_array.mean()

6.5

In [57]:
test_array.mean(axis = 0)

array([5., 6., 7., 8.])

In [58]:
test_array.std()

3.452052529534663

In [59]:
test_array.std(axis = 0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

### Other mathmatical operation

In [62]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [63]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

## Concatenate

### VSTAK/HSTAK

In [109]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])

In [110]:
np.vstack((a,b)) ## tuple 형태로 넣어주어야 한다. 즉, 괄호가 두번 사용해야 한다.

array([[1, 2, 3],
       [2, 3, 4]])

In [92]:
c = np.array([1,2,3]).reshape(-1,1)
d = np.array([2,3,4]).reshape(-1,1)
print(c)
print(d)

[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]


In [80]:
np.hstack((c,d))

array([[1, 2],
       [2, 3],
       [3, 4]])

### CONCATENATE

square braket이 두개여야 한다. 

In [112]:
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [89]:
np.concatenate((c,d), axis = 1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [105]:
a = np.array([[1, 2]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [5, 6]])

## Array operation

operations between arrays
### element-wise operations ; sum, multiply

In [113]:
test_a = np.array([[1,2,3],[2,3,4]])

In [114]:
test_a + test_a 

array([[2, 4, 6],
       [4, 6, 8]])

In [116]:
test_a * test_a

array([[ 1,  4,  9],
       [ 4,  9, 16]])

### dot product

In [120]:
test_b = np.array([1,2,3]).reshape(3,-1)
test_b

array([[1],
       [2],
       [3]])

In [119]:
test_a.dot(test_b)

array([[14],
       [20]])

### Transpose

In [122]:
test_a.T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [123]:
test_a.transpose()

array([[1, 2],
       [2, 3],
       [3, 4]])

### Broadcasting

shape이 어느정도 맞아야 한다. 
scalar만 적용되는 것이 아니라 vector, matrix 상에서도 가능하다.

In [125]:
test_a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [126]:
test_a*3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [128]:
test_a

array([[1, 2, 3],
       [2, 3, 4]])

In [130]:
test_a + np.array([3,5,7])

array([[ 4,  7, 10],
       [ 5,  8, 11]])

In [140]:
iteration_max = 1000000
vector = list(range(iteration_max))
scalar = 2

In [141]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

In [135]:
%timeit scalar_vector_product(scalar, vector)

274 ms ± 42.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [136]:
%timeit [scalar * value for value in range(iteration_max)]

157 ms ± 1.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [139]:
%timeit np.arange(iteration_max) * scalar

3.03 ms ± 446 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Comparison

In [143]:
a = np.arange(10)

In [144]:
np.any(a<10)

True

In [145]:
np.all(a>5)

False

In [147]:
np.all(a>=0)

True

In [151]:
a > 5 ## broadcating 처럼 각각의 항목을 출력해준다.

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [149]:
test_a = np.array([1,2,3])
test_b = np.array([5,4,3])

In [150]:
test_a > test_b # element-wise 처럼 각각의 항목을 출력해준다.

array([False, False, False])

In [152]:
 a = np.array([1,3,0], float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [153]:
b = np.array([True, False, False], bool)
np.logical_not(b)

array([False,  True,  True])

In [156]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True, False])

### np.where

In [160]:
a = np.array([1,3,0], float)
a

array([1., 3., 0.])

In [162]:
np.where(a >0, 3, 2) ## excel에서 if와 비슷, np.where(조건, TRUE, FALSE)

array([3, 3, 2])

In [164]:
np.where(a>0) ## 뒤에 조건이 없으면 조건을 만족하는 index 반환한다.

(array([0, 1]),)

In [168]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [169]:
np.isnan(a)

array([False,  True, False])

In [170]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin
array 내 최대값 또는 최소값의 index를 반환함

In [172]:
a = np.array([1,2,3,4,5,70,23,40])

In [173]:
np.argmax(a), np.argmin(a)

(5, 0)

In [177]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [180]:
a.max(axis = 1)

array([ 7, 88, 76])

In [182]:
a.argmax(axis =1 )

array([3, 1, 1])

In [183]:
a.argmin(axis = 1)

array([0, 2, 2])

In [184]:
a.argmin(axis = 0)

array([0, 0, 2, 2])

## Boolean index

In [185]:
 test_array = np.array([1,4,5,2,6,5,7,8], float)
test_array > 3

array([False,  True,  True, False,  True,  True,  True,  True])

In [187]:
test_array[test_array>3]

array([4., 5., 6., 5., 7., 8.])

In [189]:
A = np.array([14,253,46,35,6,57,3,45,23,55,76,84,3])

In [195]:
B = np.logical_or(A < 15, A >30)
B

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True])

In [196]:
B.astype(np.int)

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

## fancy index

In [201]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) ## 반드시 int 선언

In [202]:
a[b]

array([2., 2., 4., 8., 6., 4.])

In [203]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [204]:
A = np.array([[1,4],[9,6]], float)

In [205]:
b = np.array([0,0,1,1,0],int)
c = np.array([0,1,1,1,1],int)

In [210]:
A[b,c]

array([1., 4., 6., 6., 4.])

In [212]:
A[b]

array([[1., 4.],
       [1., 4.],
       [9., 6.],
       [9., 6.],
       [1., 4.]])

In [209]:
A.take((b,c)) ##matrix에서는 take가 역할을 못한다.

array([[1., 1., 4., 4., 1.],
       [1., 4., 4., 4., 4.]])

## numpy i/o

### CSV or TXT
* np.loadtxt("filename")
* np.savetxt("filename", 저장하려는 항목, fmt = %d, delimiter=",")

### Numpy object - npy
* np.save("filename", arr = 항목)
* np_load(file = "filename")